---
# tasks file for provisioning master instance

- name: "Install boto"
  pip:
    name: "boto"

- name: "Provisioning master instance"
  ec2:
    key_name: "{{ keypair }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    wait: "yes"
    group: "{{ sg }}"
    count_tag:
      cluster: k8s
      node: master
    exact_count: 1
    instance_tags:
      Name: "k8s-master"
      cluster: "k8s"
      node: "master"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    region: "{{ region }}"
    assign_public_ip: "{{ assign_public_ip }}"
  register: ec2_master
  notify: "Set worker instaces to 0"

- name: Run pending handlers
  meta: flush_handlers

- name: Refresh the inventory
  meta: refresh_inventory

