- name: "Terminate instances"
  ec2:
    key_name: "{{ keypair }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    group: "{{ sg }}"
    count_tag:
      cluster: k8s
      node: worker
    exact_count: 0
    instance_tags:
      Name: "k8s-worker"
      cluster: "k8s"
      node: "worker"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    region: "{{ region }}"
    assign_public_ip: "{{ assign_public_ip }}"